version: '2.2'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.5.1
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet

  logstash:
    image: docker.elastic.co/logstash/logstash-oss:6.5.1
    container_name: logstash
    volumes:
      - ~/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - 5044:5044
    networks:
      - esnet

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.5.1
    container_name: kibana
    ports:
      - 5601:5601
    networks:
      - esnet

volumes:
  esdata:
    driver: local

networks:
  esnet:
